
volumes:
  minio_data:
  pg_data:

networks:
  docman_network:

services:
  minio:
    image: bitnami/minio:2024.9.9-debian-12-r0
    ports:
      - "${MINIO_SERVER_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    networks:
      - docman_network
    volumes:
      - minio_data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

  pg:
    image: bitnami/postgresql:16.4.0-debian-12-r9
    ports:
      - "${POSTGRESQL_PORT}:5432"
    networks:
      - docman_network
    volumes:
      - pg_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}